{% set name = "pygfx" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pygfx/pygfx-{{ version }}.tar.gz
  sha256: 316043588e9454108799d30f1b00d4d88d4e3d48dd39f5963fe5c0106e28163c
  patches:
    - no_clobber_license.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - wgpu-py >=0.19.0,<0.20.0a
    - pylinalg >=0.4.1,<0.5.0a
    - freetype-py
    - uharfbuzz
    - jinja2

test:
  imports:
    - pygfx
  requires:
    - pip
    - packaging
  commands:
    - pip check
    - python -c "from pygfx import __wgpu_version_range__; from packaging.version import Version; import wgpu; assert Version(wgpu.__version__) >= Version(__wgpu_version_range__[0]), 'wgpu version too low';"
    - python -c "from pygfx import __wgpu_version_range__; from packaging.version import Version; import wgpu; assert Version(wgpu.__version__) < Version(__wgpu_version_range__[1]), 'wgpu version too high';"
    - python -c "import wgpu; print(f'wgpu version {wgpu.__version__} is just right')"

about:
  home: https://github.com/pygfx/pygfx
  summary: "Pygfx' purpose is to bring powerful and reliable visualization to the Python world. 🚀"
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
