{% set name = "pygfx" %}
{% set version = "0.1.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pygfx/pygfx-{{ version }}.tar.gz
  sha256: db31bcb7c3513389014519db90591fa39cc721e2bb4b5e3be2fbb2c47a33660d
  patches:
    - no_clobber_license.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - wgpu-py >=0.14.1,<0.16.0a
    - pylinalg >=0.4.1,<0.5.0a
    - freetype-py
    - uharfbuzz
    - jinja2

test:
  imports:
    - pygfx
  requires:
    - pip
    - packaging
  commands:
    - pip check
    - python -c "from pygfx import __wgpu_version_range__; from packaging.version import Version; import wgpu; assert Version(wgpu.__version__) > Version(__wgpu_version_range__[0]), 'wgpu version too low'; assert Version(wgpu.__version__) < Version(__wgpu_version_range__[1]), 'wgpu version too high'; print(f'wgpu version
      {wgpu.__version__} is just right')"

about:
  home: https://github.com/pygfx/pygfx
  summary: A threejs-like render engine based on wgpu
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
